type RiskGateStage = "draft_create" | "map_sync" | "structured_nodes" | "submit_review" | "approve" | "publish";

type RiskChecklistItem = {
  code: string;
  title: string;
  status: "passed" | "failed";
  message?: string;
};

type GeometryLike = {
  geometry_version?: number | string;
  route_polyline?: unknown;
  map_provider_hint?: unknown;
};

type RouteRiskGateSnapshot = {
  route_id?: string;
  route_type?: string;
  route_anchor_points?: unknown;
  map_sync_status?: string | null;
  agent_prefill_status?: string | null;
  pending_user_report_count?: number | string | null;
  source_count?: number | string | null;
  risk_count?: number | string | null;
  route_geometry?: GeometryLike;
  route_nodes?: Array<Record<string, unknown>>;
  route_exit_points?: Array<Record<string, unknown>>;
  route_risk_points?: Array<Record<string, unknown>>;
};

type RouteRiskGateResult = {
  blockers: string[];
  warnings: string[];
  risk_flags: string[];
  review_checklist: RiskChecklistItem[];
  score_summary: {
    anchor_ready: boolean;
    geometry_ready: boolean;
    navigation_ready: boolean;
    geometry_alignment_ready: boolean;
    evidence_ready: boolean;
    risk_ready: boolean;
  };
};

export type RouteRiskSummary = {
  risk_coefficient: number;
  risk_level: "low" | "medium" | "high";
  risk_color_token: "emerald" | "amber" | "rose";
  risk_reason_tags: string[];
};

function toNumber(value: unknown) {
  if (typeof value === "number" && Number.isFinite(value)) {
    return value;
  }
  if (typeof value === "string" && value.trim()) {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : 0;
  }
  return 0;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function getRecordArray(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }
  return value.filter((item): item is Record<string, unknown> => isRecord(item));
}

function countRouteAnchors(value: unknown) {
  return getRecordArray(value).filter((item) => {
    const anchorName = typeof item.anchor_name === "string" ? item.anchor_name.trim() : "";
    const point = isRecord(item.point) ? item.point : undefined;
    const coordinates = Array.isArray(point?.coordinates) ? point.coordinates : [];
    return anchorName.length > 0 || coordinates.length >= 2;
  }).length;
}

function requiresExplicitAnchors(routeType?: string) {
  return routeType === "loop" || routeType === "out_and_back";
}

function parseLineCoordinates(value: unknown) {
  if (!isRecord(value) || value.type !== "LineString" || !Array.isArray(value.coordinates)) {
    return [] as Array<[number, number]>;
  }
  return value.coordinates
    .filter((item): item is [number, number] => Array.isArray(item) && item.length >= 2)
    .map((item) => [Number(item[0]), Number(item[1])] as [number, number])
    .filter((item) => Number.isFinite(item[0]) && Number.isFinite(item[1]));
}

function parsePointCoordinates(value: unknown) {
  if (!isRecord(value) || value.type !== "Point" || !Array.isArray(value.coordinates) || value.coordinates.length < 2) {
    return undefined;
  }
  const lng = Number(value.coordinates[0]);
  const lat = Number(value.coordinates[1]);
  if (!Number.isFinite(lng) || !Number.isFinite(lat)) {
    return undefined;
  }
  return [lng, lat] as [number, number];
}

function getArtifactLabel(item: Record<string, unknown>, fallback: string) {
  const primary =
    typeof item.node_name === "string"
      ? item.node_name
      : typeof item.exit_name === "string"
        ? item.exit_name
        : typeof item.risk_title === "string"
          ? item.risk_title
          : fallback;
  return primary || fallback;
}

function getArtifactGenerationBasis(item: Record<string, unknown>) {
  return getRecordArray(item.generation_basis);
}

function isAutoGeneratedArtifact(item: Record<string, unknown>) {
  return getArtifactGenerationBasis(item).some((basis) => basis.basis_type === "geometry_rule");
}

function getArtifactGeometryVersion(item: Record<string, unknown>) {
  const geometryBasis = getArtifactGenerationBasis(item).find((basis) => basis.basis_type === "geometry_rule");
  if (!geometryBasis) {
    return undefined;
  }
  return toNumber(geometryBasis.geometry_version);
}

function getPolylineAlignmentDistanceM(point: [number, number], line: Array<[number, number]>) {
  if (line.length < 2) {
    return Number.POSITIVE_INFINITY;
  }
  const latFactor = 111320;
  const lngFactor = 111320 * Math.cos((point[1] * Math.PI) / 180);
  const projectedPoint = { x: point[0] * lngFactor, y: point[1] * latFactor };

  let minDistance = Number.POSITIVE_INFINITY;
  for (let index = 0; index < line.length - 1; index += 1) {
    const start = line[index];
    const end = line[index + 1];
    const ax = start[0] * lngFactor;
    const ay = start[1] * latFactor;
    const bx = end[0] * lngFactor;
    const by = end[1] * latFactor;
    const dx = bx - ax;
    const dy = by - ay;
    const lengthSquared = dx * dx + dy * dy;
    const ratio =
      lengthSquared <= 0
        ? 0
        : Math.max(
            0,
            Math.min(1, ((projectedPoint.x - ax) * dx + (projectedPoint.y - ay) * dy) / lengthSquared),
          );
    const closestX = ax + dx * ratio;
    const closestY = ay + dy * ratio;
    const distance = Math.hypot(projectedPoint.x - closestX, projectedPoint.y - closestY);
    if (distance < minDistance) {
      minDistance = distance;
    }
  }
  return minDistance;
}

function collectOffRouteArtifacts(
  line: Array<[number, number]>,
  items: Array<Record<string, unknown>>,
  fallbackLabel: string,
  thresholdM: number,
) {
  const labels: string[] = [];
  for (const item of items) {
    const point = parsePointCoordinates(item.point);
    if (!point) {
      continue;
    }
    const distanceM = getPolylineAlignmentDistanceM(point, line);
    if (distanceM > thresholdM) {
      labels.push(getArtifactLabel(item, fallbackLabel));
    }
  }
  return labels;
}

export function evaluateRouteRiskGate(snapshot: RouteRiskGateSnapshot, stage: RiskGateStage): RouteRiskGateResult {
  const blockers: string[] = [];
  const warnings: string[] = [];
  const riskFlags = new Set<string>();
  const geometryVersion = toNumber(snapshot.route_geometry?.geometry_version);
  const routePolyline = parseLineCoordinates(snapshot.route_geometry?.route_polyline);
  const anchorCount = countRouteAnchors(snapshot.route_anchor_points);
  const anchorReady = !requiresExplicitAnchors(snapshot.route_type) || anchorCount > 0;
  const geometryReady = routePolyline.length >= 2;
  const providerHint =
    typeof snapshot.route_geometry?.map_provider_hint === "string"
      ? snapshot.route_geometry.map_provider_hint
      : undefined;
  const routeNodes = getRecordArray(snapshot.route_nodes);
  const exitPoints = getRecordArray(snapshot.route_exit_points);
  const riskPoints = getRecordArray(snapshot.route_risk_points);
  const navigationArtifacts = [...routeNodes, ...exitPoints, ...riskPoints];
  const navigationReady = navigationArtifacts.length > 0;
  const evidenceReady = toNumber(snapshot.source_count) > 0;
  const riskReady = riskPoints.length > 0 || toNumber(snapshot.risk_count) > 0;
  const pendingUserReports = toNumber(snapshot.pending_user_report_count);

  if (!anchorReady) {
    riskFlags.add("missing_required_anchors");
    blockers.push(
      snapshot.route_type === "loop"
        ? "环线缺少中间锚点，禁止继续自动生成地图几何。"
        : "往返线缺少折返点/中间锚点，禁止继续自动生成地图几何。",
    );
  }

  if (!geometryReady && ["structured_nodes", "submit_review", "approve", "publish"].includes(stage)) {
    riskFlags.add("geometry_missing");
    blockers.push("缺少可信路线几何，请先完成地图同步。");
  }

  if (providerHint?.includes("place-search") && ["map_sync", "structured_nodes", "submit_review", "approve", "publish"].includes(stage)) {
    riskFlags.add("place_search_fallback_used");
    blockers.push("当前路线仍依赖地点搜索兜底，定位风险过高，请补更明确的锚点或人工修正后再继续。");
  }

  const staleArtifactLabels =
    geometryVersion > 0
      ? navigationArtifacts
          .filter((item) => isAutoGeneratedArtifact(item))
          .filter((item) => getArtifactGeometryVersion(item) !== geometryVersion)
          .map((item, index) => getArtifactLabel(item, `结构化点位 ${index + 1}`))
      : [];

  if (staleArtifactLabels.length > 0 && ["submit_review", "approve", "publish"].includes(stage)) {
    riskFlags.add("stale_navigation_artifacts");
    blockers.push(`路线几何已变更，需重新生成结构化点位：${staleArtifactLabels.slice(0, 3).join("、")}。`);
  }

  const offRouteLabels = geometryReady
    ? [
        ...collectOffRouteArtifacts(routePolyline, routeNodes, "关键节点", 120),
        ...collectOffRouteArtifacts(routePolyline, exitPoints, "下撤点", 120),
        ...collectOffRouteArtifacts(routePolyline, riskPoints, "风险点", 120),
      ]
    : [];

  if (offRouteLabels.length > 0 && ["submit_review", "approve", "publish"].includes(stage)) {
    riskFlags.add("artifacts_off_route");
    blockers.push(`存在点位明显落在路线外，需修正后再继续：${offRouteLabels.slice(0, 3).join("、")}。`);
  }

  if (!navigationReady && ["submit_review", "approve", "publish"].includes(stage)) {
    riskFlags.add("navigation_not_generated");
    blockers.push("地图几何已更新，但结构化点位尚未重新生成。");
  }

  if (!evidenceReady && ["approve", "publish"].includes(stage)) {
    riskFlags.add("missing_sources");
    blockers.push("缺少来源依据，禁止审核通过或发布。");
  }

  if (!riskReady && ["approve", "publish"].includes(stage)) {
    riskFlags.add("missing_risk_points");
    blockers.push("缺少风险点，禁止审核通过或发布。");
  }

  if (pendingUserReports > 0 && ["approve", "publish"].includes(stage)) {
    riskFlags.add("pending_user_reports");
    blockers.push("仍有待处理的用户上报，禁止审核通过或发布。");
  } else if (pendingUserReports > 0) {
    warnings.push(`当前仍有 ${pendingUserReports} 条待处理用户上报。`);
  }

  const reviewChecklist: RiskChecklistItem[] = [
    {
      code: "anchor_ready",
      title: "环线/往返是否具备中间锚点",
      status: anchorReady ? "passed" : "failed",
      message: anchorReady ? undefined : "缺少中间锚点时，地图同步会出现伪环线或伪往返。",
    },
    {
      code: "geometry_ready",
      title: "地图几何是否可信",
      status: geometryReady && !providerHint?.includes("place-search") ? "passed" : "failed",
      message:
        !geometryReady
          ? "尚未形成可信路线几何。"
          : providerHint?.includes("place-search")
            ? "当前几何仍依赖 place search fallback，存在明显错解风险。"
            : undefined,
    },
    {
      code: "navigation_fresh",
      title: "结构化点位是否与当前几何一致",
      status: staleArtifactLabels.length === 0 && offRouteLabels.length === 0 ? "passed" : "failed",
      message:
        staleArtifactLabels.length > 0
          ? "路线几何已更新，但结构化点位仍是旧版本。"
          : offRouteLabels.length > 0
            ? "存在点位偏离当前路线。"
            : undefined,
    },
    {
      code: "evidence_ready",
      title: "来源依据是否补齐",
      status: evidenceReady ? "passed" : "failed",
      message: evidenceReady ? undefined : "当前没有可用来源依据。",
    },
  ];

  return {
    blockers: Array.from(new Set(blockers)),
    warnings: Array.from(new Set(warnings)),
    risk_flags: Array.from(riskFlags),
    review_checklist: reviewChecklist,
    score_summary: {
      anchor_ready: anchorReady,
      geometry_ready: geometryReady,
      navigation_ready: navigationReady,
      geometry_alignment_ready: staleArtifactLabels.length === 0 && offRouteLabels.length === 0,
      evidence_ready: evidenceReady,
      risk_ready: riskReady,
    },
  };
}

export function buildRouteRiskSummary(result: Pick<RouteRiskGateResult, "blockers" | "warnings" | "risk_flags" | "score_summary">): RouteRiskSummary {
  let score = 0;
  score += Math.min(60, result.blockers.length * 25);
  score += Math.min(20, result.warnings.length * 8);
  score += Math.min(20, result.risk_flags.length * 4);

  if (!result.score_summary.anchor_ready) score += 20;
  if (!result.score_summary.geometry_ready) score += 20;
  if (!result.score_summary.geometry_alignment_ready) score += 18;
  if (!result.score_summary.navigation_ready) score += 10;
  if (!result.score_summary.evidence_ready) score += 8;
  if (!result.score_summary.risk_ready) score += 8;

  const riskCoefficient = Math.min(100, Math.round(score));
  if (riskCoefficient >= 70) {
    return {
      risk_coefficient: riskCoefficient,
      risk_level: "high",
      risk_color_token: "rose",
      risk_reason_tags: result.risk_flags,
    };
  }
  if (riskCoefficient >= 35) {
    return {
      risk_coefficient: riskCoefficient,
      risk_level: "medium",
      risk_color_token: "amber",
      risk_reason_tags: result.risk_flags,
    };
  }
  return {
    risk_coefficient: riskCoefficient,
    risk_level: "low",
    risk_color_token: "emerald",
    risk_reason_tags: result.risk_flags,
  };
}

export function shouldSkipAutoMapSync(snapshot: Pick<RouteRiskGateSnapshot, "route_type" | "route_anchor_points">) {
  return requiresExplicitAnchors(snapshot.route_type) && countRouteAnchors(snapshot.route_anchor_points) === 0;
}
